services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - "5432:5432"  # This maps port 5432 inside the container to port 5432 on your host
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: